<a href="https://colab.research.google.com/github/MANDOJU1/pandas/blob/main/08_Reshaping_data_sorting%2C_reindexing%2C_renaming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### [참고] <a href="https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf">Pandas Cheat Sheet</a>

In [1]:
import pandas as pd

In [2]:
import seaborn as sns

### [실습1]

In [3]:
# 실습을 위한 데이터 셋 로드 - 자동차

df = sns.load_dataset("mpg")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [4]:
# 행과 열
print(df.shape)
print(df.shape[0])

(398, 9)
398

### 3) sort_values()

In [5]:
# mpg 컬럼을 기준으로 정렬하기

df.sort_values('mpg')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
124,11.0,8,350.0,180.0,3664,11.0,73,usa,oldsmobile omega
...,...,...,...,...,...,...,...,...,...
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc

In [ ]:
# mpg 컬럼을 기준으로 정렬하기 - 내림차순

df.sort_values('mpg',ascending=False)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)
...,...,...,...,...,...,...,...,...,...
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d

### 4) rename

In [ ]:
df.rename?

In [ ]:
# model_year 컬럼명 변경

df.rename(columns = {'model_year':'year'})

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

### 6) reset_index() : index 를 컬럼으로 만들기(앞에서 사용함)

In [7]:
df.head()
df.set_index("cylinders")
df.reset_index()

,index,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...,...
393,393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

### 5) sort_index() : index 를 기준으로 정렬하기

In [8]:
# sort_values(컬럼명) : 컬럼을 기준으로 정렬 시
df.sort_index(ascending=False)   # 위에서 만든 index 를 기준으로 정렬

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
...,...,...,...,...,...,...,...,...,...
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu

### 7) drop(columns = ['','','']) : 괄호 안에 있는 컬럼 삭제 / drop(["",""],axis=1)

In [ ]:
# 중복 제거 : drop_duplicates() / duplicated() : True / False

df.drop(['mpg','model_year'],axis=1) # axis : 방향

,index,cylinders,displacement,horsepower,weight,acceleration,origin,name
0,0,8,307.0,130.0,3504,12.0,usa,chevrolet chevelle malibu
1,1,8,350.0,165.0,3693,11.5,usa,buick skylark 320
2,2,8,318.0,150.0,3436,11.0,usa,plymouth satellite
3,3,8,304.0,150.0,3433,12.0,usa,amc rebel sst
4,4,8,302.0,140.0,3449,10.5,usa,ford torino
...,...,...,...,...,...,...,...,...
393,393,4,140.0,86.0,2790,15.6,usa,ford mustang gl
394,394,4,97.0,52.0,2130,24.6,europe,vw pickup
395,395,4,135.0,84.0,2295,11.6,usa,dodge rampage
396,396,4,120.0,79.0,2625,18.6,usa,ford ranger
397,397,4,119.0,82.0,2720,19.4,usa,chevy s-10

In [ ]:
df.drop(columns = ['mpg','model_year'])  # df.drop(['mpg','model_year'],axis=1)

,index,cylinders,displacement,horsepower,weight,acceleration,origin,name
0,0,8,307.0,130.0,3504,12.0,usa,chevrolet chevelle malibu
1,1,8,350.0,165.0,3693,11.5,usa,buick skylark 320
2,2,8,318.0,150.0,3436,11.0,usa,plymouth satellite
3,3,8,304.0,150.0,3433,12.0,usa,amc rebel sst
4,4,8,302.0,140.0,3449,10.5,usa,ford torino
...,...,...,...,...,...,...,...,...
393,393,4,140.0,86.0,2790,15.6,usa,ford mustang gl
394,394,4,97.0,52.0,2130,24.6,europe,vw pickup
395,395,4,135.0,84.0,2295,11.6,usa,dodge rampage
396,396,4,120.0,79.0,2625,18.6,usa,ford ranger
397,397,4,119.0,82.0,2720,19.4,usa,chevy s-10

### [실습2]

In [9]:
df = pd.DataFrame({"년도":[2019,2020,2021],"미국":[2.1,2.2,2.3], "한국":[0.4,0.5,0.45], "중국":[10,13,15]})
df

     년도   미국    한국  중국
0  2019  2.1  0.40  10
1  2020  2.2  0.50  13
2  2021  2.3  0.45  15

### 1) 인덱스 생성

In [10]:
# 년도를 index로 생성하기

df = df.set_index("년도")
df

       미국    한국  중국
년도
2019  2.1  0.40  10
2020  2.2  0.50  13
2021  2.3  0.45  15

### 2) 인덱스 제거

In [11]:
# 인덱스를 컬럼으로 변경하기

df = df.reset_index('년도')
df

     년도   미국    한국  중국
0  2019  2.1  0.40  10
1  2020  2.2  0.50  13
2  2021  2.3  0.45  15

### 3) 컬럼명 변경(중국==> 홍콩)

In [ ]:
df.rename(columns={'중국':'홍콩'},inplace=True)
df

     년도   미국    한국  홍콩
0  2019  2.1  0.40  10
1  2020  2.2  0.50  13
2  2021  2.3  0.45  15